- name: Install Ruby and bundler
  become: true
  hosts: all
  tasks:
  - name: Get packages
    apt:
      name:
        - git
        - ruby-full
        - ruby-bundler
        - build-essential
      state: present
      update_cache: true
